"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Globe2, LockKeyhole, MapPin, ShieldCheck, Sparkles, Users } from "lucide-react";

type View = "privacy" | "ready" | "preferences" | "review" | "reveal" | "signal" | "priorities" | "research";
type Preferences = { remote: boolean; travel: string; visits: string; wearable: boolean; procedures: string[]; outcomes: string[] };
const defaultPreferences: Preferences = { remote: true, travel: "Within 2 hours", visits: "Up to 4 a year", wearable: true, procedures: [], outcomes: ["Fatigue", "Arm & shoulder function", "Independence"] };
const prioritySeed = [
  { id: "fatigue", title: "What drives day-to-day fatigue?", votes: 88, color: "#d96d58" },
  { id: "function", title: "What best preserves arm and shoulder function?", votes: 76, color: "#22877e" },
  { id: "mobility", title: "How can studies reduce mobility burden?", votes: 51, color: "#8066af" },
  { id: "home", title: "Can home measures track meaningful change?", votes: 45, color: "#d49e36" },
];

export default function Home() {
  const [view, setView] = useState<View>("privacy");
  const [understood, setUnderstood] = useState(false);
  const [step, setStep] = useState(0);
  const [prefs, setPrefs] = useState<Preferences>(defaultPreferences);
  const [consent, setConsent] = useState(false);
  const [joined, setJoined] = useState(false);
  const [votes, setVotes] = useState<Record<string, number>>({});

  useEffect(() => { if (localStorage.getItem("cg-fshd-joined") === "yes") setJoined(true); }, []);
  const memberCount = 126 + (joined ? 1 : 0);
  const totalVotes = Object.values(votes).reduce((total, count) => total + count, 0);
  const priorities = useMemo(() => prioritySeed.map((p) => ({ ...p, votes: p.votes + (votes[p.id] || 0) })).sort((a, b) => b.votes - a.votes), [votes]);
  const save = () => { localStorage.setItem("cg-fshd-joined", "yes"); localStorage.setItem("cg-fshd-preferences", JSON.stringify(prefs)); setJoined(true); setView("reveal"); };

  return <main>
    <div className="banner"><Sparkles size={13} /> Fictional prototype · FSHD facts cited below · all community data is synthetic</div>
    <header><button className="brand" onClick={() => setView("privacy")}><b>C</b>Common<span>Ground</span></button><p>FSHD research community</p><button className="research-link" onClick={() => setView("research")}>Study-team preview</button></header>
    {view === "privacy" && <Privacy understood={understood} setUnderstood={setUnderstood} continue={() => setView("ready")} />}
    {view === "ready" && <Ready begin={() => setView("preferences")} signal={() => setView(joined ? "signal" : "privacy")} />}
    {view === "preferences" && <PreferencesForm step={step} setStep={setStep} prefs={prefs} setPrefs={setPrefs} review={() => setView("review")} back={() => setView("ready")} />}
    {view === "review" && <Review prefs={prefs} consent={consent} setConsent={setConsent} back={() => setView("preferences")} save={save} />}
    {view === "reveal" && <Reveal remote={prefs.remote} continue={() => setView("signal")} />}
    {view === "signal" && <Signal members={memberCount} joined={joined} remote={joined && prefs.remote ? 79 : 78} priorities={() => setView("priorities")} researcher={() => setView("research")} />}
    {view === "priorities" && <Priorities priorities={priorities} totalVotes={totalVotes} votes={votes} cast={(id) => totalVotes < 3 && setVotes({ ...votes, [id]: (votes[id] || 0) + 1 })} back={() => setView("signal")} />}
    {view === "research" && <Research members={memberCount} back={() => setView(joined ? "signal" : "privacy")} />}
  </main>;
}

function Privacy({ understood, setUnderstood, continue: next }: { understood: boolean; setUnderstood: (v: boolean) => void; continue: () => void }) {
  return <section className="privacy-page"><div className="intro"><p className="eyebrow">FSHD RESEARCH COMMUNITY</p><h1>Before anything else: your information has boundaries.</h1><p className="lede">Facioscapulohumeral muscular dystrophy can affect muscle strength, fatigue, pain, and mobility differently from person to person. This space helps make research less burdensome—not to judge whether anyone qualifies.</p><p className="sources">Condition context: <a href="https://www.fshdsociety.org/living-with-fshd/understanding-fshd/" target="_blank">FSHD Society</a> · <a href="https://rarediseases.info.nih.gov/diseases/9941/facioscapulohumeral-muscular-dystrophy" target="_blank">NIH GARD</a></p></div><div className="boundaries"><article className="public"><span>PUBLIC</span><h2>Nothing yet.</h2><p>You are not creating a profile, choosing an alias, or sharing your diagnosis publicly in this first step.</p></article><article className="private"><span>PRIVATE</span><h2>Your future preferences.</h2><p>If you continue, you may optionally describe what research participation could feel workable for you.</p></article><article className="aggregate"><span>RESEARCHER-VISIBLE</span><h2>Only grouped patterns.</h2><p>Study teams can eventually see community-level patterns—never your identity, health record, or individual answers.</p></article></div><div className="ack"><label><input type="checkbox" checked={understood} onChange={(e) => setUnderstood(e.target.checked)} /><span>I understand this is a synthetic prototype. It does not provide medical advice, determine eligibility, or enroll me in a study.</span></label><button className="primary" disabled={!understood} onClick={next}>I understand <ArrowRight size={17} /></button></div></section>;
}

function Ready({ begin, signal }: { begin: () => void; signal: () => void }) { return <section className="ready-page"><div className="soft-orbit"><LockKeyhole size={28} /></div><p className="eyebrow">YOU’RE IN CONTROL</p><h1>Nothing has been collected.</h1><p className="lede">The next step is optional: you can say what research participation could look like for you. Your answers will only ever contribute to grouped, synthetic community patterns in this demo.</p><button className="primary" onClick={begin}>Choose participation preferences <ArrowRight size={17} /></button><button className="quiet" onClick={signal}>I’ve already contributed</button></section> }

function PreferencesForm({ step, setStep, prefs, setPrefs, review, back }: { step: number; setStep: (n: number) => void; prefs: Preferences; setPrefs: (p: Preferences) => void; review: () => void; back: () => void }) {
  const toggle = (value: string) => setPrefs({ ...prefs, procedures: prefs.procedures.includes(value) ? prefs.procedures.filter((p) => p !== value) : [...prefs.procedures, value] });
  const toggleOutcome = (value: string) => { const outcomes = prefs.outcomes.includes(value) ? prefs.outcomes.filter((p) => p !== value) : prefs.outcomes.length < 3 ? [...prefs.outcomes, value] : prefs.outcomes; setPrefs({ ...prefs, outcomes }); };
  const titles = ["What participation could feel workable?", "What kinds of study activities feel comfortable?", "What should research make better?"];
  return <section className="form-page"><aside><button className="back" onClick={back}><ChevronLeft size={17} />Leave for now</button><p className="eyebrow">OPTIONAL PREFERENCES</p><h1>Share only what helps you be represented.</h1><p>These are participation preferences, not clinical information.</p><ol>{["Logistics", "Study activities", "Research outcomes"].map((name, index) => <li className={index === step ? "current" : index < step ? "done" : ""} key={name}><b>{index < step ? <Check size={12} /> : index + 1}</b>{name}</li>)}</ol></aside><article className="form-card"><p className="step">STEP {step + 1} OF 3</p><h2>{titles[step]}</h2>{step === 0 && <><p className="help">No answer here says whether you can join a study. It only helps describe what a more practical study could look like.</p><Choice label="Remote visits" description="I could consider some visits from home" checked={prefs.remote} onChange={() => setPrefs({ ...prefs, remote: !prefs.remote })} /><label>Travel that could feel manageable<select value={prefs.travel} onChange={(e) => setPrefs({ ...prefs, travel: e.target.value })}><option>Within 2 hours</option><option>Within 1 hour</option><option>Remote only</option><option>Not sure</option></select></label><label>In-person visits you could consider<select value={prefs.visits} onChange={(e) => setPrefs({ ...prefs, visits: e.target.value })}><option>Up to 4 a year</option><option>Up to 2 a year</option><option>Only if necessary</option><option>Not sure</option></select></label></>}{step === 1 && <><p className="help">Select any activities you might consider. You can leave everything unselected.</p><Choice label="Wearable device" description="For example, an activity or movement sensor" checked={prefs.wearable} onChange={() => setPrefs({ ...prefs, wearable: !prefs.wearable })} /><p className="field-label">Procedures you might consider</p><div className="chips">{["Blood sample", "Muscle imaging", "Strength assessment", "Home diary"].map((item) => <button className={prefs.procedures.includes(item) ? "selected" : ""} onClick={() => toggle(item)} key={item}>{prefs.procedures.includes(item) && <Check size={14} />}{item}</button>)}</div></>}{step === 2 && <><p className="help">Choose up to three outcomes that you want research to improve or better understand.</p><div className="outcomes">{["Fatigue", "Arm & shoulder function", "Independence", "Mobility", "Pain", "Sleep", "Daily activities"].map((item) => <button key={item} onClick={() => toggleOutcome(item)} className={prefs.outcomes.includes(item) ? "selected" : ""}>{prefs.outcomes.includes(item) && <b>{prefs.outcomes.indexOf(item) + 1}</b>}{item}</button>)}</div></>}<footer><button className="quiet" onClick={() => step ? setStep(step - 1) : back()}>{step ? "Back" : "Leave for now"}</button><button className="primary" onClick={() => step === 2 ? review() : setStep(step + 1)}>{step === 2 ? "Review my choices" : "Continue"}<ChevronRight size={17} /></button></footer></article></section>;
}

function Choice({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="choice"><div><b>{label}</b><span>{description}</span></div><button aria-pressed={checked} onClick={onChange} className={checked ? "toggle on" : "toggle"}><i /></button></div> }

function Review({ prefs, consent, setConsent, back, save }: { prefs: Preferences; consent: boolean; setConsent: (v: boolean) => void; back: () => void; save: () => void }) { return <section className="review-page"><p className="eyebrow">ONE LAST CHECK</p><h1>Here’s the boundary before you add your signal.</h1><div className="review-card"><div><span>GROUPED WITH THE COMMUNITY</span><b>{prefs.remote ? "Remote-visit comfort" : "No remote preference"} · {prefs.travel} travel · {prefs.visits} · {prefs.outcomes.join(", ")}</b></div><div><span>NEVER SHARED FROM THIS DEMO</span><b>Your name, contact information, health record, diagnosis proof, and individual answers</b></div></div><label className="consent"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /><span>I understand that expressing a research preference is not consent to a study and does not determine eligibility.</span></label><div className="actions"><button className="quiet" onClick={back}>Go back</button><button className="primary" disabled={!consent} onClick={save}>Add my protected signal <ArrowRight size={17} /></button></div></section> }

function Reveal({ remote, continue: next }: { remote: boolean; continue: () => void }) { return <section className="reveal-page"><div className="constellation"><i /><i /><i /><i /><i /><i /><strong>127</strong></div><p className="eyebrow">YOUR CONTRIBUTION IS NOW A PATTERN</p><h1><span>126</span><em>→</em><span>127</span></h1><h2>You made the community signal a little clearer.</h2><p>{remote ? "The remote-participation pattern has changed because you chose to share a preference." : "Your priorities are now part of the protected community pattern."}</p><button className="primary" onClick={next}>See the protected signal <ArrowRight size={17} /></button></section> }

function Signal({ members, joined, remote, priorities, researcher }: { members: number; joined: boolean; remote: number; priorities: () => void; researcher: () => void }) { return <section className="signal-page"><div className="signal-heading"><div><p className="eyebrow">FSHD COMMUNITY SIGNAL</p><h1>What a community can show without exposing its members.</h1><p>Every figure below is fictional and synthetic. Values below five are grouped to protect people.</p></div><span className="protected"><ShieldCheck size={17} />Aggregate only</span></div><div className="stats"><Stat icon={<Users />} number={String(members)} label="synthetic members" /><Stat icon={<Globe2 />} number="14" label="synthetic countries" /><Stat icon={<MapPin />} number={remote + "%"} label="comfortable with remote visits" /><Stat icon={<LockKeyhole />} number="<5" label="small groups suppressed" /></div><div className="signal-grid"><article className="map-card"><p className="eyebrow">COMMUNITY REACH</p><div className="dot-map" aria-label="A decorative dotted world map showing synthetic geographic reach"><span>• • • · · • •</span><span>· • • • • · •</span><span>• · · • · • ·</span><span>· • • · • · •</span></div><p>14 countries represented in the fictional cohort.</p></article><article className="barrier-card"><p className="eyebrow">WHAT MAKES STUDIES HARDER</p><h2>Burden is part of study design.</h2>{[["Travel distance", 64], ["Unpredictable fatigue", 58], ["Caregiver availability", 36]].map(([label, value]) => <div className="bar" key={String(label)}><span>{label}</span><i><b style={{ width: value + "%" }} /></i><em>{value}%</em></div>)}</article><article className="priority-card"><p className="eyebrow">WHAT MEMBERS WANT STUDIED</p><h2>Research priorities</h2><ol><li><b>1</b>Fatigue variability</li><li><b>2</b>Arm & shoulder function</li><li><b>3</b>Mobility burden</li></ol><button className="text-link" onClick={priorities}>Add your priorities <ArrowRight size={15} /></button></article></div>{joined && <p className="join-note"><Check size={16} /> Your synthetic contribution is included in this local demo.</p>}<button className="researcher-text" onClick={researcher}>View protected study-team comparison</button></section> }
function Stat({ icon, number, label }: { icon: React.ReactNode; number: string; label: string }) { return <article><span>{icon}</span><b>{number}</b><small>{label}</small></article> }

function Priorities({ priorities, totalVotes, votes, cast, back }: { priorities: typeof prioritySeed; totalVotes: number; votes: Record<string, number>; cast: (id: string) => void; back: () => void }) { return <section className="priorities-page"><button className="back" onClick={back}><ChevronLeft size={17} />Community signal</button><div className="priority-head"><div><p className="eyebrow">RESEARCH PRIORITIES</p><h1>Choose what deserves attention.</h1><p>These are research questions, not treatment advice.</p></div><span><b>{3 - totalVotes}</b> votes left</span></div>{priorities.map((item, index) => <article className="proposal" key={item.id}><b>{index + 1}</b><div><p className="eyebrow">A COMMUNITY QUESTION</p><h2>{item.title}</h2><i><em style={{ width: Math.min(item.votes, 100) + "%", background: item.color }} /></i><small>{item.votes} synthetic community votes</small></div><button className={votes[item.id] ? "voted" : "vote"} disabled={totalVotes >= 3} onClick={() => cast(item.id)}>{votes[item.id] ? <><Check size={15} />{votes[item.id]}</> : "Vote"}</button></article>)}</section> }

function Research({ members, back }: { members: number; back: () => void }) { const [remoteFirst, setRemoteFirst] = useState(true); const feasibility = remoteFirst ? 79 : 42; return <section className="research-page"><header><button className="brand light" onClick={back}><b>C</b>CommonGround</button><p><LockKeyhole size={14} />Aggregate-only study-team preview</p><button className="exit" onClick={back}>Exit preview</button></header><div><p className="eyebrow">FICTIONAL STUDY-DESIGN TOOL</p><h1>Test burden before you write the protocol.</h1><p className="lede">This is a community-level planning aid. It cannot see a person, contact anyone, or make a clinical decision.</p><div className="study-grid"><article><span>COHORT SNAPSHOT</span><b>{members}</b><p>synthetic FSHD community members</p><small>14 countries · 78% remote-ready</small></article><article className="scenario"><span>VISIT MODEL</span><button className={remoteFirst ? "selected" : ""} onClick={() => setRemoteFirst(true)}><b>Remote-first</b><small>Monthly home check-ins + 2 site visits</small></button><button className={!remoteFirst ? "selected" : ""} onClick={() => setRemoteFirst(false)}><b>Site-heavy</b><small>Monthly site visits + travel</small></button></article><article className="result"><span>COMMUNITY FEASIBILITY SIGNAL</span><b>{feasibility}%</b><p>{remoteFirst ? "would consider this participation shape" : "could consider this participation shape"}</p><hr /><strong>{remoteFirst ? "Why it changes" : "Design trade-off"}</strong><p>{remoteFirst ? "Remote visits respond to travel distance and fatigue—two leading barriers in this fictional cohort." : "More travel may exclude people whose mobility or fatigue makes frequent site visits impractical."}</p></article></div><p className="governance"><ShieldCheck size={16} /> Future study concepts require verification, patient-advisory review, ethics review, and explicit opt-in outreach.</p></div></section> }
